### PR TITLE
Isabelle: test case for natural numbers

### PR DESCRIPTION
**Pull request by larsrh**
I'm using this example in a paper draft, but it also serves as a nice test case.

The interesting thing is that Z3 can't prove the postcondition of `+`.

### CODE REVIEW

**Comment by larsrh** [comment]
Oops, looks like some change in Leon broke my code. Please don't merge yet.

**Comment by larsrh** [comment]
Pending https://groups.google.com/d/msg/leon-dev/ulXuirfrcwI/c6mlHD2cBQAJ.

**Comment by larsrh** [comment]
Good for merging now. Strings are left unspecified in Isabelle, so no proofs about them are possible.

**Comment by colder** [comment]
Merged Thanks

**Pull request merged**
