### PR TITLE
make larabot test Isabelle

### PR DESCRIPTION
**Pull request by larsrh**
*fingers crossed* :rocket:

### CODE REVIEW

**Comment by larsrh** [comment]
The failure in `regression:test` is not my fault, but the `isabelle:test` failure seems to be genuine. I'll investigate.

**Comment by larsrh** [comment]
Minimal failing example:

```scala
import leon._
import leon.annotation._
import leon.collection._
import leon.lang._

object Lists {

  def lemma7[A, B](xs: List[A]) =
    (xs.zip(Nil[B]()) == Nil[(A, B)]()).holds

  def lemma7_check =
    (lemma7[Int, Int](Nil())).holds

}
```

**Comment by larsrh** [comment]
I did a bisect and the first commit which exhibits a problem is e6f9e4b490129dde96265db72dadb038c1a58b2c, albeit with a different error message (apparently it produced ill-typed programs). Some time after that, I start seeing duplicate function definitions (for the above example, two copies of `lemma7`). My initial suspicion is a change in `replaceFunDefs` which I use in the `IsabelleAdaptationPhase`.

**Comment by samarion** [comment]
That's possible, the function just underwent a fairly large change. I'll try to take a look at what's going wrong in your case.

**Comment by larsrh** [comment]
@samarion Thanks, that's great. I also dug into the sources and added some more debug statements to the adaptation phase. Here's the input program:

```scala
import leon._
import leon.annotation._
import leon.collection._
import leon.lang._

object Lists$0 {
  def lemma7$0[A$0, B$0](xs$0 : List$0[A$0]): Boolean =  {
    xs$0.zip$1[B$0](Nil$0[B$0]()) == Nil$0[(A$0, B$0)]()
  } ensuring {
    (holds$1 : Boolean) => holds$1
  }
  
  def lemma7_check$0(): Boolean =  {
    lemma7$0[Int, Int](Nil$0[Int]())
  } ensuring {
    (holds$2 : Boolean) => holds$2
  }
}
```

And here's the output:

```scala
import leon._
import leon.annotation._
import leon.collection._
import leon.lang._

object Lists$0 {
  def lemma7$1[A$0, B$0](xs$0 : List$0[A$0], dummy$0 : Dummy$0[B$0]): Boolean =  {
    xs$0.zip$1[B$0](Nil$0[B$0]()) == Nil$0[(A$0, B$0)]()
  } ensuring {
    (holds$1 : Boolean) => holds$1
  }
  
  def lemma7_check$0(): Boolean =  {
    lemma7$0[Int, Int](Nil$0[Int]())
  } ensuring {
    (holds$2 : Boolean) => holds$2
  }
}
```

It looks like the function call in `lemma7_check$0()` did not get rewritten.

**Comment by samarion** [comment]
Oh actually I may already have fixed that. Could you rebase on master and try again please?

**Comment by larsrh** [comment]
I rebased, but I'm still seeing the problem locally.

**Comment by larsrh** [comment]
Isabelle tests are working :shipit:

**Comment by colder** [comment]
Merged, thanks!

**Pull request closed without merging**
