### PR TITLE
DSL for proofs (including tests and documentation)

### PR DESCRIPTION
**Pull request by sstucki**
Review @mantognini, @manoskouk.

### CODE REVIEW

**Comment by mantognini** [comment]
I just skimmed through the changes and it looks alright. But Travis complains with [`Failed to compile verification/proof/measure/Meas.scala`](https://travis-ci.org/epfl-lara/leon/jobs/76251036#L1381). No idea why though.

**Comment by colder** [comment]
Meas.scala seems to refer to some different Rational library. For instance, isPositive is not defined in Leon's Rationals, also RationalSpecs can't be found. Were those based on the Rational class we had in exercises for SAV?

**Comment by sstucki** [comment]
@colder: yes, we use a custom Rational library based on the SAV exercise. It's in the same directory as Meas.scala. I wasn't aware that there's a standard Rational library. I guess I could rewrite the test to use that instead.

**Comment by colder** [comment]
Ok, so the issue is that we compile each file of test-cases individually, so you can't have these "packages of files". I think Manos merged the files and should merge it soon

**Comment by manoskouk** [comment]
Merged. Thanks for the contribution!

**Comment by larsrh** [comment]
Should the stuff in `leon.proof` also be annotated with `@library`?

**Comment by colder** [comment]
Good catch. Since it didn't generate VCs it slipped under the radar.

**Pull request closed without merging**
