### PR TITLE
Minor nits in documentation

### PR DESCRIPTION
**Pull request by Sumith1896**
/cc @ravimad

### CODE REVIEW

**Comment by MikaelMayer** [comment]
Hi Sumith, can you please update your PR?

**Comment by ravimad** [comment]
Hi Sumith,
Thanks for the fixes. Also feel free to add more explanation or examples to the documentation. Btw, I have not added lazy, higher-order extension yet. It will be added soon.

**Comment by Sumith1896** [comment]
Larabot isn't running I think. I updated this PR couple of hours back.

**Comment by ravimad** [comment]
Okay I have done a manual merge.

**Comment by Sumith1896** [comment]
Cheers!

**Pull request merged**
