### PR TITLE
no recursion into lets

### PR DESCRIPTION
**Pull request by regb**

### CODE REVIEW

**Comment by samarion** [comment]
Specs in the current leon can be nested within a sequence of let defs. See 
preconditionOf, postconditionOf, etc.

**Comment by regb** [comment]
yes, but there was an exists wrapper around, so the Let case was redundant

**Comment by samarion** [comment]
Ohh, indeed, I didn't notice that :) It would be a bit more efficient to implement this without the exists though...

**Comment by regb** [comment]
I wasn't sure if it was safe. What happened if an Ensuring is deep down in the tree?

**Comment by samarion** [comment]
Well if it isn't discovered by the recursive version of hasSpec (that recurses through lets as well), it won't be in postconditionOf anyway. It will be translated into an Assert within the solvers, so it won't disappear completely, but then hasSpec doesn't check for asserts anyway...

**Comment by regb** [comment]
I tried the recursive definitions, but some test failed. Will try to look into that but for now I merged that one as it fixes a performance issue with xlang

**Pull request merged**
