### PR TITLE
add `Nat` type to Leon library

### PR DESCRIPTION
**Pull request by larsrh**

### CODE REVIEW

**Comment by MikaelMayer** [comment]
Can you please update your branch and then notify me?

**Comment by larsrh** [comment]
Just done so but according to @regb larabot is having some problems right now.

**Comment by regb** [comment]
I'm building the updated branch here: https://github.com/epfl-lara/leon/tree/topic/nats-rebase

**Comment by regb** [comment]
For some reason, I'm not able to get the build working with the Nat type in the library. Any idea why?

**Comment by larsrh** [comment]
What are the failures you're seeing?

**Comment by regb** [comment]
Nothing particular, the process just dies after a while... http://laraquad4.epfl.ch:9000/epfl-lara/leon/build/1593/11093
But you know, it's the larabot, so ...

**Comment by larsrh** [comment]
It's a little difficult for me to figure out the precise causes, given that I haven't changed anything in the tests. I'm trying to run the regression tests locally right now; will report back when that's done.

**Comment by larsrh** [comment]
I've found the problem. There was an assertion which couldn't be proved by the SMT solvers.

**Comment by larsrh** [comment]
@regb We're green!

**Comment by regb** [comment]
thanks, well done!

**Pull request merged**
