### PR TITLE
Small updates

### PR DESCRIPTION
**Pull request by larsrh**

### CODE REVIEW

**Comment by MikaelMayer** [comment]
Is there a way to remove "copying isabelle files" which shows in the log when compiling leon?

**Comment by larsrh** [comment]
I can disable it in the plugin, but why? It's the same kind of message as `Compiling 415 Scala sources …`.

**Comment by MikaelMayer** [comment]
Hello Lars,
Why are we copying these files if they did not change?
I understand we show that we are compiling files since they changed.
Is it also the case with these Isabelle files?
Best regards,
Mikaël

**Comment by larsrh** [comment]
Oh right, now I understand. The Isabelle solver needs to find the sources at runtime to load them into the Isabelle process. The `sbt-libisabelle` plugin hence needs to copy them somewhere SBT is willing to put into the Leon package. In theory you could only copy them if they changed, but since it's a cheap copy operation (not compilation), there's no real point there. Also this would mean to detect changes in some way. I'm not sure whether SBT offers some library for that.

**Comment by regb** [comment]
This log seems fine to me, let's not get into the risky task of tweaking sbt ;p

**Comment by larsrh** [comment]
I just noticed that there's a genuine failure in `isabelle:test` due to a subtle change in libisabelle. Could someone with shell access to laraquad please delete the folder `/localhome/laraservices/.local/share/libisabelle`?

**Comment by MikaelMayer** [comment]
Done.

2016-06-28 10:27 GMT+02:00 Lars Hupel <notifications@github.com>:

**Comment by larsrh** [comment]
Closing/reopening to trigger rebuild.

**Comment by larsrh** [comment]
Well, that didn't work – I'll leave it to you then :smile:

**Comment by manoskouk** [comment]
Merged, thanks!

**Pull request merged**
